services:
  - type: web
    name: comiru-ocr-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comiru_ocr_db
          property: connectionString

