services:
  - type: web
    name: comiru-ocr-app-doc
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: bash -c "python manage.py migrate && gunicorn sqlServerProject.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comiru_ocr_db
          property: connectionString
