services:
  - type: web
    name: comiru-ocr-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn sqlServerProject.wsgi
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comiru_ocr_db
          property: connectionString
    migrationsCommand: python manage.py migrate

