# Generated by Django 5.0.14 on 2025-04-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_child_birth_date_child_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='juku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ご利用中の塾'),
        ),
    ]
