# Generated by Django 5.0.14 on 2025-04-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_child_juku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='user',
            new_name='parent',
        ),
    ]
