# Generated by Django 5.0.14 on 2025-04-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child'),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonevaluation',
            name='child',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.child'),
            preserve_default=False,
        ),
    ]
