# Generated by Django 5.0.14 on 2025-04-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child'),
        ('ocr', '0002_lessonevaluation_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonevaluation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_evaluations', to='accounts.child'),
        ),
    ]
